### ISSUE TITLE
loose: true break the lib

### ISSUE THREAD

**Issue by gorangajic** [theKashey/react-locky#25]
`document.querySelectorAll` is not an `Array` and does not have `.concat` method.

Without loose: true
```jsx
var freeNodes = _toConsumableArray(document.querySelectorAll("[".concat(LOCKY_TRANSPARENT, "=\"true\"]")));
```
With loose: true
```jsx
var freeNodes = document.querySelectorAll("[" + LOCKY_TRANSPARENT + "=\"true\"]").concat();
```

**Comment by theKashey** [comment]
:coneofshame:
I did notice that locky is not _locking_, but forgot to check "why". Thank you a report.

Released as v1.5.4, please update.
